baseURL = "https://midorigreen.github.io/blog"
languageCode = "jp"
title = "Green Software Engineer Blog"
theme = "beautifulhugo"
canonifyurls = true
publishDir = "docs"

pygmentsCodeFences = true
pygmentsUseClasses = true
[Params]
    UseChroma = true
